import {StyleSheet} from 'react-native';
import Color from '../../utils/color';
import {
  horizontalScale,
  verticalScale,
  moderateScale,
} from '../../utils/metrics';
export default StyleSheet.create({
  container: {
    height: verticalScale(184),
    width: horizontalScale(103),
    backgroundColor: Color.ghostWhite,
    marginHorizontal: horizontalScale(3),
    borderRadius: moderateScale(12),
    justifyContent: 'space-between',
    overflow: 'hidden',
  },
  btn: {
    height: horizontalScale(36),
    width: horizontalScale(36),
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Color.platinum,
    borderRadius: moderateScale(18),
    overflow: 'hidden',
    marginLeft: horizontalScale(6),
    marginTop: verticalScale(6),
    borderWidth: moderateScale(1),
    borderColor: Color.ultramarineBlue,
  },
  txtContainer: {
    shadowColor: Color.vampireBlack,
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 1,
    marginBottom: verticalScale(8),
    elevation: 2,
  },
  txt: {
    marginLeft: horizontalScale(7),
    color: Color.white,
    fontSize: moderateScale(14),
    fontWeight: '600',
  },
  // img: {
  //   height: horizontalScale(32),
  //   width: horizontalScale(32),
  //   borderRadius: moderateScale(18),
  //   overflow: 'hidden',
  // },
  bgImg: {
    height: '100%',
    width: '100%',
    position: 'absolute',
  },
  addStoryBgImg: {
    height: '67%',
    position: 'relative',
  },
  addStoryTxt: {
    marginLeft: 0,
    alignSelf: 'center',
    marginTop: 3,
    color: Color.vampireBlack,
    textAlign: 'center',
    fontSize: moderateScale(13),
  },
  addStoryContainer: {
    height: verticalScale(184),
    width: horizontalScale(103),
    backgroundColor: Color.ghostWhite,
    marginHorizontal: horizontalScale(3),
    borderRadius: moderateScale(12),
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: Color.platinum,
    justifyContent: undefined,
  },
  addStoryBtn: {
    backgroundColor: Color.ghostWhite,
    height: 36,
    width: 36,
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    marginTop: -18,
    paddingLeft: 1,
  },
});
